### PR TITLE
Hi, Anthony, committing the text file

### PR DESCRIPTION
**Pull request by janisvillarroel**
this is my pull request

### CODE REVIEW

**Comment by anthonykulis** [comment]
Awesome. Ok. So lets identify the flow of this app first. Are you familiar with the builder pattern?

**Comment by janisvillarroel** [comment]
Yes , it's a creational pattern

**Comment by anthonykulis** [comment]
Ok, then we need to identify the creation steps to build an order. I think its pretty straightforward, but would like your opinion on it as well.

To me, for ordering, its simply

```
1. add meal
2. add meal
3. add meal
...
...
N. build
```
But how should we add meals? This is the part I want you to supply an opinion on. Do we on `addMeal()` delegate to the builder to decide what meal to add, pass a meal builder, or what? Since we are not going to do any human interfacing on this, I really would like an opinion.

**Comment by anthonykulis** [comment]
Also, I am on your hangout that you started, if you need to use that as well, please feel free.

**Comment by janisvillarroel** [comment]
image

**Comment by anthonykulis** [comment]
the return of void is *ok* in `addMeal`, but can we return OrderBuilderInterface? That way I can do

```java
new OrderBuilder().addMeal(new Meal()).addMeal(new Meal()).build()
```

Also, lets update the class name of `Order` to `OrderBuilder`, and the interface to `OrderBuilder`. The way we have it now is the `Order` class is building itself, and I think that kind of violates the concept.

**Comment by janisvillarroel** [comment]
image

**Comment by anthonykulis** [comment]
For `OrderBuilder`, we can drop the `toString` here. I think we forgot to take it out. 
screen shot 2017-03-31 at 6 52 56 pm

**Comment by anthonykulis** [comment]
For `MealBuilderInterface`, we forgot `build`
screen shot 2017-03-31 at 6 52 59 pm

**Comment by janisvillarroel** [comment]
image

**Comment by anthonykulis** [comment]
Ok. For our `MealBuilderInterface`, I was thinking we do not want to allow the user to pass the fries, drinks, etc. To me, if I was to click a button that says "Big Mac Meal", I would be doing something like:

```java
new BigMacMealBuilder().makeLargeSize().withCoke().build();
new CheeseBurgerMealBuilder().makeMediumSize().withIcedTea().build();
new QuarterPounderMealBuilder().withDietCoke().build();
```

I like the idea of this over passing the classes in anemic `addSandwich` style. The reason for this is that its very easy to read and maintain. For example, if McDonalds decided to change up the BigMac, we can encapsulate the instantiation of that in the builder and update as needed, and basically never affect the classes using the builder.  

So while that may require use to have more methods and classes, its a million times more expressive.

**Comment by anthonykulis** [comment]
Oh, let me also point out, this should be legal as well.

```java
new BigMacMealBuilder().withCoke().addApplePie().build();
new HamburgerMealBuider().withCoke().addSundae().build();
```

Since we are headed this route, its apparent we cannot build a meal without a drink, so we will need to update the interface  for build to also throw an exception on that being null.

**Comment by anthonykulis** [comment]
Which brings me to an implementation note. While I am thinking about it, our `Order` needs to be able to print the total price. This means the `Meal` should have a "sub price" in it as well. That way when we do `Order::toString`, we can easily just sum up each meal with an aggregator.

**Comment by janisvillarroel** [comment]
image

**Comment by anthonykulis** [comment]
99% of the way there. lets drop `makeRegular` because we can assume thats default. And instead of `addSandwich`, we will instead implement `BigMacMealBuilder`, `HamburgerMealBuilder` and that will determine which sandwich we use.

**Comment by anthonykulis** [comment]
oh. we can also drop `addFry` and assume all meals come with fries as per our spec sheet.

**Comment by anthonykulis** [comment]
janis, ugh. sorry. thats what i get for multitasking and having a meeting at the same time. I just realized these 3 methods are off. We will start off as a "regular" meal. This means the fries and drink are small. From there we can `makeMediumSized` or `makeLargeSize`. 
screen shot 2017-03-31 at 7 55 12 pm

**Comment by anthonykulis** [comment]
or do you want to leave it as it is. I think you have a better idea now that i think about it more. lol

**Comment by janisvillarroel** [comment]
image

**Comment by janisvillarroel** [comment]
i would like to keep ip,  added the others builders and also the Meal class, do you have any comment?

**Comment by anthonykulis** [comment]
Looks great! Do we need the headache of `BigDecimal`? I do not think we will have round off error on this. Up to you though.

**Comment by janisvillarroel** [comment]
Hi, Anthony

image

**Comment by anthonykulis** [comment]
Morning! Hey I'm about to pick up and drive home. On lake fishing. It may
take me about 1.5 hours to get home. But I have my cell and can reply here

**Comment by janisvillarroel** [comment]
And our MealBuilder like this, what do you think?

image

**Comment by janisvillarroel** [comment]
as you said all private attributes will get mutators and accesors

**Comment by anthonykulis** [comment]
It looks great. I'm currently stranded on the lake! My boat won't start. So
my wife is meeting me at the closest dock. I will have to then go get my
truck and the come back and get the boat. So I probably will be hit and
miss. If you could do the pojo uml, the. We will be good to go and code

**Comment by janisvillarroel** [comment]
Ok, I'll put get and set methods, after this , can I do the code? as a next step

**Comment by anthonykulis** [comment]
Sure, but we need the POJO UML, so the sandwiches, fries, etc.

**Comment by janisvillarroel** [comment]
Hi, Anthony
I complete our DC 
image

**Comment by janisvillarroel** [comment]
image

**Comment by anthonykulis** [comment]
Can we leverage polymorphism? As these quantity of items grow in any
architecture, the way you have it we will be required to work off of
String. For instance, BigMac now comes in three sizes. If we had to
implement those and when using a collection we'd have to do string
comparisons to see which we had.

Life would be easier if we could do

BigMac kingBigMac = new KingBigMac()

**Comment by janisvillarroel** [comment]
[Class Diagram.pdf](https://github.com/anthonykulis/mcdonalds-kiosk/files/888451/Class.Diagram.pdf)

**Comment by anthonykulis** [comment]
Hmm. Rereading that and I could have been clearer. We need to leverage the
4 pillars of OOP at all times. In the UML provided we are not. A BigMac
is-a Sandwich. A QuarterPounder is-a Sandwich. A LargeFry is-a Fry, a
LargeCoke is-a Drink. The reason for this is because with all is-a
relationships they share properties but have different values. In our case,
these properties most likely are going to be immutable, so let's make them
immutable where applicable.

**Comment by anthonykulis** [comment]
Now when McDonalds asks us to now offer root beer from the kiosk, we can
extend appropriately. This reinforces open/closed and dependency inversion
principles.

**Comment by anthonykulis** [comment]
I have to drive an hour and a half south. So I will be on highway and
cannot respond. When I get to where I need to go, if you have or need
anything, I will reply.

**Comment by janisvillarroel** [comment]
Before we continue, i hope that everything went well yesterday, with you and your wife. I couldn't ask you. we could do, do you want something like this Meal <-BigMac<-(BigMacLarge,BigMacMedium,BigMacRegular)

**Comment by janisvillarroel** [comment]
image

**Comment by anthonykulis** [comment]
Awesome

**Comment by janisvillarroel** [comment]
image

**Comment by anthonykulis** [comment]
LargeCoke is-a coke. DietCoke is-a coke.

**Comment by anthonykulis** [comment]
And a Coke is-a Drink

**Comment by janisvillarroel** [comment]
I was thinking to put a boolean Flag on Drink like isDiet, but I had some doubts

**Comment by anthonykulis** [comment]
To much dependency on knowledge how to use the class the . Also, I was
thinking, do we need String name with the accessors? Can't we just use
toString. Seems like it might be on the fringe of DRY violations. Ok.
Getting in highway finally. I'll be available in about one hour

**Comment by janisvillarroel** [comment]
ok, I think is a good idea use toString

**Comment by janisvillarroel** [comment]
I have a problem, is a restriction on Lucid

image

**Comment by anthonykulis** [comment]
Ugh! Ok. Then go without the remaining UML and just do the code. I can do a
review on it if needed. Or handwrite it and post a cell picture. Either way
is fine. I think we are in a position to write code now

**Comment by janisvillarroel** [comment]
image

image

image

image

**Comment by anthonykulis** [comment]
Looks great. I don't see the diet version of coke and a IceTeaLarge is-a
IcedTea. I think those should be abstracted as such

**Comment by janisvillarroel** [comment]
Anthony, I have to go out. If you have more suggestions please write it

**Comment by anthonykulis** [comment]
Ok

**Comment by anthonykulis** [comment]
@janisvillarroel - spoke with jeremy today, he is wanting code by end of day tuesday so he can make a decision. I think you are right on with what I want to see, so lets take in those last few considerations I commented on and produce out this code.

**Comment by janisvillarroel** [comment]
About the let me see, I updated our design

**Comment by janisvillarroel** [comment]
image

**Comment by janisvillarroel** [comment]
image

**Comment by janisvillarroel** [comment]
image

**Comment by anthonykulis** [comment]
looks great

**Comment by janisvillarroel** [comment]
image

**Comment by janisvillarroel** [comment]
image

**Comment by janisvillarroel** [comment]
image

**Comment by janisvillarroel** [comment]
that is everything

**Comment by anthonykulis** [comment]
Looks fantastic. Go ahead and lets code this up.

**Comment by janisvillarroel** [comment]
Hi, Anthony 
are you there?

**Comment by anthonykulis** [comment]
hey!

**Comment by janisvillarroel** [comment]
Hi, I have the code, how do you prefer that I upload it???

**Comment by anthonykulis** [comment]
through the pull request. commit it locally on your computer. if you need to merge, to your local master, then push the your remote. this repo is linked, so I will be able to code review it

**Comment by janisvillarroel** [comment]
done, Anthony , can you see it?

**Comment by anthonykulis** [comment]
yes,its in the pr

**Comment by janisvillarroel** [comment]
Great,I have to go out, any question or suggestion, Anthony please write me, i'll check it when I back

**Comment by anthonykulis** [comment]
sure! thanks for going thru it all. it was a pleasure. i need to do all the analysis stuff on my end and pass it along to jeremy. hopefully will have my end done tonight.

**Pull request merged**
